config/routes.rb
Rails.application.routes.draw do
  root                        to: "top#index"
  resources :top,           only: :index
  resources :lists,       except: %i(index, show) do
    resources :cards,     except: :index
  end
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list
  validates :title, length: { in: 1..20 }
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :cards, dependent: :destroy

  validates :title, length: { in: 1..20 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
  validates :name, presence: true, length: { in: 1..20 }
  has_many :lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i(name))
  end

  private

  def set_(model, param)
    model.find(params[:"#{param}"]) unless params[:"#{param}"].nil?
  rescue
    nil
  end

  def redirect_to_root_by_nil_of(parameter)
    redirect_to root_path if parameter.nil?
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i(show edit update destroy)
  before_action :set_list, only: %i(new create)

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to :root
    else
      render :new
    end
  end

  def show
    redirect_to_root_by_nil_of(@card)
  end

  def edit
    redirect_to_root_by_nil_of(@card)
  end

  def update
    if @card.update_attributes(card_params)
      redirect_to :root
    else
      render :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to :root
  end

  private

  def card_params
    params.require(:card).permit(:title, :memo, :list_id)
  end

  def set_card
    @card = set_(Card, :id)
  end

  def set_list
    @list = set_(List, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i(edit update destroy)

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to :root
    else
      render :new
    end
  end

  def edit
    redirect_to_root_by_nil_of(@list)
  end

  def update
    if @list.update_attributes(list_params)
      redirect_to :root
    else
      render :edit
    end
  end

  def destroy
    if @list.destroy
      redirect_to :root
    else
      render :edit
    end
  end

  private

  def list_params
    params.require(:list).permit(:title).merge(user: current_user)
  end

  def set_list
    @list = set_(List, :id)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @lists = List.includes(:cards).where(user: current_user).order(created_at: :asc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def make_title(given_title)
    if given_title.empty?
      "Tasklist"
    else
      given_title
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cards/edit.html.erb
<%= provide(:title, @card.title) %>
<div class="cardseditPage">
  <div class='container'>
    <%= form_with model: @card, url: list_card_path , html: { class: 'cardseditForm' } do |f| %>
      <div class="cardseditForm_title">
        <%= f.label :title, "Card Title" %> <span>(1〜20 characters)</span>
        <%= f.text_field :title, class: "form-control", autocomplete: "off" %>
      </div>
      <div class="cardseditForm_memo">
        <%= f.label :memo %> <span>(1〜200 characters)</span>
        <%= f.text_area :memo, class: "form-control" %>
      </div>
      <div class="text-center"><%= f.submit "Update", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/cards/new.html.erb
<%= provide(:title, "Create New Card") %>
<div class="cardsnewPgae">
  <div class='container'>
    <%= form_with model: @card, url: list_cards_path, html: { class: 'cardsnewForm' } do |f| %>
      <%= f.hidden_field :list_id, value: @list.id %>
      <div class="cardsnewForm_title">
        <%= f.label :title, "Card Title" %> <span>(1〜20 characters)</span>
        <%= f.text_field :title, autofocus: true, autocomplete: "off", class: "form-control" %>
      </div>
      <div class="cardsnewForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, autofocus: true, class: "form-control" %>
        <div class="text-center"><%= f.submit "Create", class: "submitBtn" %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/cards/show.html.erb
<%= provide(:title, @card.title) %>
<div class='cardsdetailPage'>
  <div class="container">
    <div class="cardsContents">
      <div class="cardsContents_title">
        <div>Card Title</div>
        <h2><%= @card.title %></h2>
      </div>
      <div class="cardsContents_memo">
        <div>Memo</div>
        <div><%= @card.memo %></div>
      </div>
      <div class="cardsContents_btnArea">
        <%= link_to 'Edit', edit_list_card_path(@card.list, @card), class: "edit_btn" %>
        <%= link_to 'Delete', list_card_path(@card.list, @card), class: "delete_btn", method: :delete, data: { confirm: "Are you sure to delete?" } %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<title><%= make_title(yield(:title)) %></title>

<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="nav">
    <ul class="header_menu">
      <li class="nav-link">
        <%= link_to current_user.name, edit_user_registration_path %>
      </li>

      <li class="header_menu_title">
        <%= link_to "#{current_user.name}'s Tasklist", root_path, class: "nav-link" %></li>
      <li>
        <ul class="header_menu_inner">
          <li><%= link_to "Create List", new_list_path, class: "nav-link listNew" %></li>
          <li><%= link_to "Logout", destroy_user_session_path, class: "nav-link", method: :delete %></li>
        </ul>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/head" %>
  </head>
  <body>
  <%= render partial: "layouts/header" if user_signed_in? %>

  <%= yield %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/lists/edit.html.erb
<%= provide(:title, @list.title) %>
<div class="listseditPage">
  <div class="container">
    <%= form_with model: @list, url: list_path , html: { class: 'listsForm' } do |f| %>
      <%= f.label :title, "List Title" %> <span>(1〜20 characters)</span>
      <%= f.text_field :title, class: "form-control listName", autocomplete: "off"%>
      <div class="text-center"><%= f.submit "Update", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<%= provide(:title, "Create New List") %>
<div class="listsnewPage">
  <div class="container">
    <%= form_with model: @list, url: lists_path, class: "new_list" do |f| %>
      <%= f.label :title, "List Title" %> <span>(1〜20 characters)</span>
      <%= f.text_field :title, autofocus: true, autocomplete: "off", class: "form-control listName" %>
      <div class="text-center">
        <%= f.submit "Create", class: "submitBtn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/top/index.html.erb
<%= provide(:title, "Tasklist") %>
<div class="topPage">
  <div class="listsWrapper">
    <% @lists.each do |list| %>
      <div class="lists">
        <div class="lists_header">
          <h2 class="lists_header_title"><%= list.title %></h2>
          <div class="lists_header_action">
            <%= link_to content_tag(:i, '', class: 'fas fa-trash'), list, method: :delete, data: {confirm: "Are you sure to delete?"} %>
            <%= link_to content_tag(:i, '', class: 'fas fa-pen'), edit_list_path(list) %>
          </div>
        </div>
        <div class="cardsWrapper">
          <% list.cards.each do |card| %>
            <%= link_to list_card_path(list, card), class: "cardsDetail_link" do %>
              <div class="cards">
                <h3 class="cards_title"><%= card.title %></h3>
              </div>
            <% end %>
          <% end %>
          <div class="addCards">
            <i class="far fa-plus-square"></i>
            <%= link_to "New Card", new_list_card_path(list), class: "addCards_link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>